# Generated by Django 3.2.25 on 2026-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='captured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='disputed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='refunded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attempted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
